# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# Renaming ? Change the README badge.
name: Build
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  BASE_CHECKS:
    name: Base Checks
    runs-on: ubuntu-latest
    env:
      GHUB_USER: ${{ secrets.GHUB_USER }}
      GHUB_PERSONAL_ACCESS_TOKEN: ${{ secrets.GHUB_PERSONAL_ACCESS_TOKEN }}
      SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
      SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
      - name: Perform base checks
        run: ./gradlew build deployLocal